1 commit for 0.19 fixes
waterlink/crystal-mysql pull request #46
Opened 2016-09-20 13:53 UTC by puppetpies

Hi there,

I've just came across a small compilation problem on the new 0.19 release.

Just replaced the as with : just 3 lines.

Regards,

Brian Hood

2016-09-20 21:53 UTC, waterlink commented
I see a failure on Travis. Wasn't it `thing.as(Type)` instead of `thing : Type` ?

2016-09-20 22:13 UTC, DougEverly commented on src/mysql/connection.cr
> +      result = LibMySQL.options(@handle, option, value : Void*)
Try `value.as Void*`

2016-09-20 22:13 UTC, DougEverly commented on src/mysql/types.cr
> +        "'#{String.new(value : Slice(UInt8))}'"
Try `value.as Slice(UInt8)`

2016-09-20 22:13 UTC, DougEverly commented on src/mysql/types.cr
> +        %{'#{(value : Time).to_utc.to_s("%F %T")}'}
`value.as Time`

2016-09-20 22:14 UTC, DougEverly commented on src/mysql/types.cr
> +        %{'#{(value : Time).to_utc.to_s("%F %T")}'}
`as` keyword is now a pseudo-method. Try the above changes.

2016-09-20 22:15 UTC, DougEverly requested changes
`as` keyword is now a pseudo-method.

2016-09-21 02:10 UTC, puppetpies commented
Interesting i will have a read.

Fix in place.

2016-09-21 06:41 UTC, merged

2016-09-21 06:41 UTC, waterlink commented
Thanks!

2016-09-21 06:47 UTC, waterlink commented
I have published this as a v0.4.4